### ISSUE TITLE
 Looks for polygon create program from set of segments

### ISSUE THREAD

**Issue by DigitCell** [rowanwins/sweepline-intersections#14]
include your project in mine project successfully, but I simplify part of code (move out debug and utils parts, as not needed), all work well.
But yes, solver return to small information:
best on my view is to receive from solver  list of points with id of constraints and constraints list with indexes of points.

Main ides why write this topic, is to ask you add some support of polygon generation from intersection of segments, I'm try to find some light weight lib, but all that find work incorrect. Work well only CGAL, but it to heavy for my project.

Thanks, for sharing such good peace of code
Alexander

**Comment by rowanwins** [comment]
Hi @DigitCell 

I'm glad the code was useful to you. 

I currently have a pull request / branch open that looks to provide additional information in the results
https://github.com/rowanwins/sweepline-intersections/pull/13
It's not quite finalised but you might find it useful to refer to. I've been using it internally on an buffer/offset algorithm and it seems to be working.

I would be interested to see your polygon generation algorithm - are you referring to boolean operations like 'union' and 'difference'?

Regards,
Rowan

**Comment by DigitCell** [comment]
Polygon boolean operations is support by Clipper Lib, it is not new, but work.  The task is to generate polygons from intersection of segments(lines). Your code quit near, half of task is done, find all intersect points, another half is to generate list of polygons from this intersection.
