### ISSUE TITLE
test fails for 'chileKinked.geojson'

### ISSUE THREAD

**Issue by armantorkzaban** [rowanwins/sweepline-intersections#15]
First of all let me thank you on behalf of my team for your great efforts in developing this library and many other essential ones.  
We have ported it to Dart. You may find it here: https://github.com/dartclub/sweepline_intersections

Our issue is with the 'chileKinked.geojson' which fails in the corresponding test. Sweepline produces an empty list of intersection even though the 'properties' expects '2'

We wondered what we might have done wrong and wanted to ask if you could help us. 

* All other tests pass perfectly fine. 
Att: @lukas-h

**Comment by lukas-h** [comment]
@armantorkzaban Have you checked if the tests fails in the JS version too?

**Comment by armantorkzaban** [comment]
No, I could not accurately test it.

**Comment by rowanwins** [comment]
It works in the js version - you can run `npm run test` and it'll run all the tests, including checking that `chileKinked.geojson` finds 2 intersection points. So it looks like something has gone astray in your port. 

I can't say I know anything about Dart so not sure I can help terribly much sorry.

**Comment by armantorkzaban** [comment]
Thank you for your quick reply. I found the bug, it was a silly mistake from my side and I was not covering the case for MultiPolygon. 
Btw, now that we are here, the following seem to be redundant. And perhaps you might want to change it: 
- https://github.com/rowanwins/sweepline-intersections/blob/099622c776979a3d905237d82efb481835778ceb/src/utils.js#L5
- https://github.com/rowanwins/sweepline-intersections/blob/099622c776979a3d905237d82efb481835778ceb/src/utils.js#L25 (it returns false in 'else' anyways)
