### ISSUE TITLE
Hole near to the border returns self intersection

### ISSUE THREAD

**Issue by Falke-Design** [rowanwins/sweepline-intersections#16]
Demo: https://plnkr.co/edit/foSV8nwmXnSWBhGT

Data: 
```
{
  "type": "MultiPolygon",
  "coordinates": [
    [
      [[0,0], [1, -1], [2, 2], [0,0]]
      ,[[0.3, 0.3], [0.6, 0.6], [0.5, -0.5], [0.3, 0.3]]
    ]
  ]
};
```
![grafik](https://user-images.githubusercontent.com/19800037/197332161-eff41a7b-9f81-4938-974c-9a31841f9b38.png)

Zoom 19:
![grafik](https://user-images.githubusercontent.com/19800037/197332177-87554dd4-9411-4771-b696-c0f66788b24d.png)

**Comment by rowanwins** [comment]
Hi @Falke-Design 

I'm not sure if I've got the best answer but I _think_ this might be a projection issue. 

If you modify the map to display the data in a non-projected manner using `L.CRS.Simple` then you don't see any little gaps.
````
var map = L.map('map', {
	crs: L.CRS.Simple,
	center: [0, 0],
	zoom: 3,
	maxZoom: 20
});
````
Thinking about it mathematically I would also expect an intersection point at `[0.5, -0.5]` on a segment between `[0, 0], [1, -1]`.

So I think this is one of those quirks when data is presented when with projections.

Make sense?

**Comment by Falke-Design** [comment]
Yeah I understand ... 😕 I think it would be to much work to include a CRS option?

**Comment by rowanwins** [comment]
So if you run the analysis with the coords in WebMercator then no intersections will be returned, as per what you're expecting visually. 
I don't think it's this libraries job to project coordinates for you, you're better off using proj4 or @turf/projection for that.

eg
````
{
  "type": "MultiPolygon",
  "coordinates": [
    [
      [
        [
          0.0,
          0.0
        ],
        [
          111319.490793273565941,
          -111325.142866385082016
        ],
        [
          222638.981586547131883,
          222684.208505544025684
        ],
        [
          0.0,
          0.0
        ]
      ],
      [
        [
          33395.847237982066872,
          33395.999833380206837
        ],
        [
          66791.694475964133744,
          66792.915264250957989
        ],
        [
          55659.745396636782971,
          -55660.451865421520779
        ],
        [
          33395.847237982066872,
          33395.999833380206837
        ]
      ]
    ]
  ]
}
````
